begin;

do $$
begin
  if to_regclass('public.world_controls') is null then
    raise exception 'public.world_controls does not exist';
  end if;
  if to_regprocedure('public.is_game_admin()') is null then
    raise exception 'public.is_game_admin() does not exist';
  end if;
end $$;

alter table public.world_controls
  add column if not exists great_tribulation_started_at timestamptz,
  add column if not exists great_tribulation_ends_at timestamptz,
  add column if not exists great_tribulation_last_ended_at timestamptz,
  add column if not exists great_tribulation_cooldown_until timestamptz,
  add column if not exists great_tribulation_next_auto_check_at timestamptz,
  add column if not exists great_tribulation_last_trigger text;

create table if not exists public.great_tribulation_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_id uuid,
  detail jsonb not null default '{}'::jsonb,
  happened_at timestamptz not null default now()
);

alter table public.great_tribulation_events enable row level security;
revoke all on table public.great_tribulation_events from anon, authenticated;

create or replace function public.admin_great_tribulation_status()
returns public.world_controls
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_is_admin boolean := false;
  v_row public.world_controls%rowtype;
begin
  select coalesce(public.is_game_admin(), false) into v_is_admin;
  if not v_is_admin then
    raise exception 'admin permission required' using errcode = '42501';
  end if;

  select * into v_row
  from public.world_controls
  where id = 1;

  if not found then
    raise exception 'world_controls id=1 not found';
  end if;

  return v_row;
end;
$$;

create or replace function public.admin_great_tribulation_start(
  p_force boolean default false
)
returns public.world_controls
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_is_admin boolean := false;
  v_row public.world_controls%rowtype;
begin
  select coalesce(public.is_game_admin(), false) into v_is_admin;
  if not v_is_admin then
    raise exception 'admin permission required' using errcode = '42501';
  end if;

  select * into v_row
  from public.world_controls
  where id = 1
  for update;

  if not found then
    raise exception 'world_controls id=1 not found';
  end if;

  if coalesce(v_row.great_tribulation_active, false) then
    return v_row;
  end if;

  if not coalesce(p_force, false)
     and v_row.great_tribulation_cooldown_until is not null
     and now() < v_row.great_tribulation_cooldown_until then
    raise exception '大天劫冷卻至 %，可使用強制啟動。', v_row.great_tribulation_cooldown_until;
  end if;

  update public.world_controls
  set
    great_tribulation_active = true,
    great_tribulation_started_at = now(),
    great_tribulation_ends_at = now() + interval '4 hours',
    great_tribulation_last_trigger = case when p_force then 'admin_force' else 'admin_manual' end,
    great_tribulation_next_auto_check_at = null
  where id = 1
  returning * into v_row;

  insert into public.great_tribulation_events(event_type, actor_id, detail)
  values (
    case when p_force then 'admin_force_start' else 'admin_manual_start' end,
    auth.uid(),
    jsonb_build_object(
      'started_at', v_row.great_tribulation_started_at,
      'ends_at', v_row.great_tribulation_ends_at,
      'forced', coalesce(p_force, false)
    )
  );

  return v_row;
end;
$$;

create or replace function public.admin_great_tribulation_end(
  p_apply_cooldown boolean default true
)
returns public.world_controls
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_is_admin boolean := false;
  v_row public.world_controls%rowtype;
begin
  select coalesce(public.is_game_admin(), false) into v_is_admin;
  if not v_is_admin then
    raise exception 'admin permission required' using errcode = '42501';
  end if;

  select * into v_row
  from public.world_controls
  where id = 1
  for update;

  if not found then
    raise exception 'world_controls id=1 not found';
  end if;

  update public.world_controls
  set
    great_tribulation_active = false,
    great_tribulation_last_ended_at = now(),
    great_tribulation_cooldown_until =
      case when coalesce(p_apply_cooldown, true) then now() + interval '48 hours' else null end,
    great_tribulation_next_auto_check_at =
      case when coalesce(p_apply_cooldown, true) then now() + interval '48 hours' else now() + interval '1 hour' end,
    great_tribulation_ends_at = null,
    great_tribulation_last_trigger =
      case when coalesce(p_apply_cooldown, true) then 'admin_end' else 'admin_end_no_cooldown' end
  where id = 1
  returning * into v_row;

  insert into public.great_tribulation_events(event_type, actor_id, detail)
  values (
    case when coalesce(p_apply_cooldown, true) then 'admin_end' else 'admin_end_no_cooldown' end,
    auth.uid(),
    jsonb_build_object(
      'cooldown_until', v_row.great_tribulation_cooldown_until,
      'apply_cooldown', coalesce(p_apply_cooldown, true)
    )
  );

  return v_row;
end;
$$;

revoke all on function public.admin_great_tribulation_status() from public, anon;
revoke all on function public.admin_great_tribulation_start(boolean) from public, anon;
revoke all on function public.admin_great_tribulation_end(boolean) from public, anon;

grant execute on function public.admin_great_tribulation_status() to authenticated;
grant execute on function public.admin_great_tribulation_start(boolean) to authenticated;
grant execute on function public.admin_great_tribulation_end(boolean) to authenticated;

notify pgrst, 'reload schema';

commit;

select
  true as installed,
  'V14.5-STAGE1-TRIBULATION-20260721'::text as schema_version,
  has_function_privilege('authenticated', 'public.admin_great_tribulation_status()', 'EXECUTE') as status_ready,
  has_function_privilege('authenticated', 'public.admin_great_tribulation_start(boolean)', 'EXECUTE') as start_ready,
  has_function_privilege('authenticated', 'public.admin_great_tribulation_end(boolean)', 'EXECUTE') as end_ready;
