(()=>{'use strict';
let recipes=[];const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function row(item='',qty=1){return `<div class="recipe-ing-row"><input class="recipe-ing-id" placeholder="材料物品 ID" value="${esc(item)}"><input class="recipe-ing-qty" type="number" min="1" value="${Number(qty)||1}"><button type="button" class="btn red recipe-ing-del">移除</button></div>`}
function addRow(item='',qty=1){$('recipeIngredients').insertAdjacentHTML('beforeend',row(item,qty));bindRows()}
function bindRows(){document.querySelectorAll('.recipe-ing-del').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>b.parentElement.remove())})}
function clearForm(){$('recipeId').value='';$('recipeCode').value='';$('recipeName').value='';$('recipeDesc').value='';$('recipeOutput').value='';$('recipeOutputQty').value=1;$('recipeRate').value=100;$('recipeMinLv').value=1;$('recipeCost').value=0;$('recipeEnabled').checked=true;$('recipePublic').checked=true;$('recipeReturn').checked=false;$('recipeAI').checked=false;$('recipeIngredients').innerHTML='';addRow()}
async function load(){const {data,error}=await sb.rpc('craft_recipe_list',{p_include_hidden:true});if(error)return toast('配方載入失敗：'+error.message);recipes=Array.isArray(data)?data:[];render()}
function render(){const box=$('recipeAdminList');if(!recipes.length){box.innerHTML='<p class="notice">尚未建立配方。</p>';return}box.innerHTML=recipes.map(r=>`<div class="recipe-admin-item"><div><b>${esc(r.name)}</b><small>${esc(r.code)}｜${r.ingredients.map(i=>esc(i.item_id)+'×'+i.qty).join(' + ')} → ${esc(r.output_item_id)}×${r.output_qty}</small></div><span class="pill ${r.enabled?'on':''}">${r.enabled?'啟用':'停用'}</span><button class="btn" data-edit="${r.id}">編輯</button><button class="btn red" data-del="${r.id}">刪除</button></div>`).join('');box.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>edit(b.dataset.edit)));box.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>del(b.dataset.del)))}
function edit(id){const r=recipes.find(x=>String(x.id)===String(id));if(!r)return;$('recipeId').value=r.id;$('recipeCode').value=r.code;$('recipeName').value=r.name;$('recipeDesc').value=r.description||'';$('recipeOutput').value=r.output_item_id;$('recipeOutputQty').value=r.output_qty;$('recipeRate').value=Math.round(Number(r.success_rate)*100);$('recipeMinLv').value=r.min_level;$('recipeCost').value=r.lingshi_cost;$('recipeEnabled').checked=!!r.enabled;$('recipePublic').checked=!!r.is_public;$('recipeReturn').checked=!!r.failure_returns_materials;$('recipeAI').checked=!!r.allow_ai;$('recipeIngredients').innerHTML='';r.ingredients.forEach(i=>addRow(i.item_id,i.qty));$('recipeFormCard').scrollIntoView({behavior:'smooth'})}
async function save(){const ingredients=[...document.querySelectorAll('.recipe-ing-row')].map((e,n)=>({item_id:e.querySelector('.recipe-ing-id').value.trim(),qty:Number(e.querySelector('.recipe-ing-qty').value),sort_order:n+1})).filter(x=>x.item_id&&x.qty>0);const payload={id:$('recipeId').value||null,code:$('recipeCode').value.trim(),name:$('recipeName').value.trim(),description:$('recipeDesc').value.trim(),output_item_id:$('recipeOutput').value.trim(),output_qty:Number($('recipeOutputQty').value)||1,success_rate:(Number($('recipeRate').value)||100)/100,min_level:Number($('recipeMinLv').value)||1,lingshi_cost:Number($('recipeCost').value)||0,enabled:$('recipeEnabled').checked,is_public:$('recipePublic').checked,failure_returns_materials:$('recipeReturn').checked,allow_ai:$('recipeAI').checked,sort_order:100,ingredients};const {error}=await sb.rpc('admin_craft_recipe_save',{p_recipe:payload});if(error)return toast('儲存失敗：'+error.message);toast('配方已儲存');clearForm();await load()}
async function del(id){if(!confirm('確定刪除此配方？'))return;const {error}=await sb.rpc('admin_craft_recipe_delete',{p_recipe_id:id});if(error)return toast('刪除失敗：'+error.message);toast('配方已刪除');await load()}
function init(){const main=$('adminMain');if(!main||$('recipeFormCard'))return;main.insertAdjacentHTML('beforeend',`<section class="card" id="recipeFormCard"><h2>萬法煉造配方控制台</h2><div class="notice">材料組合可隨時修改，例如 1＋2＋3＝4，也可改成 1＋2＋5＝4。物品欄位請填遊戲物品 ID。</div><input id="recipeId" type="hidden"><div class="grid3" style="margin-top:10px"><div class="field"><label>配方代碼</label><input id="recipeCode" placeholder="例如 refine_stone"></div><div class="field"><label>配方名稱</label><input id="recipeName"></div><div class="field"><label>成品物品 ID</label><input id="recipeOutput"></div><div class="field"><label>成品數量</label><input id="recipeOutputQty" type="number" min="1" value="1"></div><div class="field"><label>成功率（%）</label><input id="recipeRate" type="number" min="1" max="100" value="100"></div><div class="field"><label>最低等級</label><input id="recipeMinLv" type="number" min="1" value="1"></div><div class="field"><label>靈石費用</label><input id="recipeCost" type="number" min="0" value="0"></div></div><div class="field" style="margin-top:10px"><label>配方說明</label><textarea id="recipeDesc"></textarea></div><h3>材料</h3><div id="recipeIngredients"></div><button type="button" class="btn jade" id="recipeAddIngredient">新增材料</button><div class="recipe-flags"><label><input id="recipeEnabled" type="checkbox" checked> 啟用</label><label><input id="recipePublic" type="checkbox" checked> 玩家可見</label><label><input id="recipeReturn" type="checkbox"> 失敗返還材料</label><label><input id="recipeAI" type="checkbox"> AI 可用</label></div><div class="row"><button type="button" class="btn gold" id="recipeSave">儲存配方</button><button type="button" class="btn" id="recipeClear">新增／清空</button></div></section><section class="card"><h2>現有配方</h2><div id="recipeAdminList"></div></section>`);$('recipeAddIngredient').addEventListener('click',()=>addRow());$('recipeSave').addEventListener('click',save);$('recipeClear').addEventListener('click',clearForm);clearForm();load()}
const old=window.enterAdmin;if(typeof old==='function')window.enterAdmin=async function(){await old.apply(this,arguments);setTimeout(init,0)};document.addEventListener('DOMContentLoaded',()=>setTimeout(init,500));
})();
