(()=>{
'use strict';
const S={tab:'official',auctions:[],tx:[],config:null,busy:false,ready:false};
const el=id=>document.getElementById(id);
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('zh-TW');
const rpc=async(name,args={})=>{if(typeof sb==='undefined')throw new Error('Supabase 尚未初始化');const {data,error}=await sb.rpc(name,args);if(error)throw error;return data};
function itemName(s){return s?.name||s?.equipment?.name||s?.item_name||s?.item_id||'未命名拍品'}
function renderTabs(){const box=el('auctionAdminTabs');if(!box)return;const tabs=[['official','官方拍品投放'],['history','拍賣紀錄／強制結束'],['transactions','玩家交易紀錄'],['settings','拍賣參數設定']];box.innerHTML=tabs.map(([id,t])=>`<button type="button" class="btn ${S.tab===id?'gold':''}" data-a-tab="${id}">${t}</button>`).join('');box.querySelectorAll('[data-a-tab]').forEach(b=>b.addEventListener('click',()=>{S.tab=b.dataset.aTab;renderTabs();render()}))}
function officialView(){const now=new Date(Date.now()+10*60000);now.setSeconds(0,0);const local=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);return `<div class="notice">建立官方拍品後會直接進入拍賣資料庫。拍品 JSON 至少應包含 name；可保留 item_id、kind、detail 等資料。</div><div class="grid" style="margin-top:10px"><div class="field"><label>官方拍品 JSON</label><textarea id="aaOfficialJson" class="auction-admin-json">{"kind":"item","item_id":"9001","name":"護器符","detail":"淬鍊失敗時保護法寶"}</textarea></div><div><div class="field"><label>起標價</label><input id="aaOfficialPrice" type="number" min="100" step="100" value="1000"></div><div class="field" style="margin-top:8px"><label>開始時間</label><input id="aaOfficialStart" type="datetime-local" value="${local}"></div><div class="field" style="margin-top:8px"><label>拍賣分鐘</label><input id="aaOfficialMinutes" type="number" min="5" max="1440" value="30"></div><button type="button" class="btn gold" id="aaCreateOfficial" style="width:100%;margin-top:10px">投放官方拍品</button></div></div>`}
function historyView(){return `<div class="grid3"><div class="field"><label>狀態</label><select id="aaStatus"><option value="all">全部</option><option value="scheduled">尚未開始</option><option value="live">競標中</option><option value="ended">已結束</option><option value="settled">已結算</option><option value="cancelled">已取消</option></select></div><div class="field"><label>搜尋拍品／賣家／UUID</label><input id="aaSearch" placeholder="關鍵字"></div><div class="field"><label>&nbsp;</label><button type="button" class="btn jade" id="aaSearchBtn">查詢</button></div></div><div class="auction-admin-table auction-admin-scroll" id="aaHistoryRows" style="margin-top:10px"></div>`}
function txView(){return `<div class="grid"><div class="field"><label>玩家 UUID（留空查全部）</label><input id="aaPlayerId" placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"></div><div class="field"><label>&nbsp;</label><button type="button" class="btn jade" id="aaTxBtn">查詢交易紀錄</button></div></div><div class="auction-admin-table auction-admin-scroll" id="aaTxRows" style="margin-top:10px"></div>`}
function settingsView(){const c=S.config||{};return `<div class="grid3"><div class="field"><label>拍賣啟用</label><select id="aaEnabled"><option value="true" ${c.enabled!==false?'selected':''}>啟用</option><option value="false" ${c.enabled===false?'selected':''}>停用</option></select></div><div class="field"><label>每日場次（逗號分隔）</label><input id="aaTimes" value="${h((c.session_times||['12:30','20:00']).join(','))}"></div><div class="field"><label>每場分鐘</label><input id="aaDuration" type="number" min="5" max="1440" value="${Number(c.session_duration_minutes||30)}"></div><div class="field"><label>最低起標價</label><input id="aaMinPrice" type="number" min="1" value="${Number(c.min_start_price||100)}"></div><div class="field"><label>每次加價</label><input id="aaIncrement" type="number" min="1" value="${Number(c.bid_increment||100)}"></div><div class="field"><label>每日上架上限</label><input id="aaDailyLimit" type="number" min="0" max="100" value="${Number(c.daily_listing_limit??1)}"></div><div class="field"><label>防狙擊觸發秒數</label><input id="aaThreshold" type="number" min="0" max="3600" value="${Number(c.anti_snipe_threshold_seconds??60)}"></div><div class="field"><label>防狙擊延長秒數</label><input id="aaExtension" type="number" min="0" max="3600" value="${Number(c.anti_snipe_extension_seconds??60)}"></div><div class="field"><label>官方賣家名稱</label><input id="aaOfficialName" value="${h(c.official_seller_name||'萬寶樓官方')}"></div></div><button type="button" class="btn gold" id="aaSaveConfig" style="width:100%;margin-top:10px">儲存拍賣參數</button>`}
function render(){const b=el('auctionAdminBody');if(!b)return;b.innerHTML=S.tab==='official'?officialView():S.tab==='history'?historyView():S.tab==='transactions'?txView():settingsView();bind();if(S.tab==='history')renderHistory();if(S.tab==='transactions')renderTx()}
function bind(){el('aaCreateOfficial')?.addEventListener('click',createOfficial);el('aaSearchBtn')?.addEventListener('click',()=>searchHistory(true));el('aaTxBtn')?.addEventListener('click',()=>searchTx(true));el('aaSaveConfig')?.addEventListener('click',saveConfig)}
async function load(silent=false){if(S.busy)return;S.busy=true;try{S.config=await rpc('auction_get_config');if(S.tab==='history')await searchHistory(false);if(S.tab==='transactions')await searchTx(false);render();S.ready=true;if(!silent&&typeof toast==='function')toast('拍賣後台已更新')}catch(e){const body=el('auctionAdminBody');if(body)body.innerHTML=`<div class="notice">拍賣後台載入失敗：${h(e.message)}<br>請確認已成功執行 V14.4 FIX3 SQL，並使用管理員帳號登入。</div>`;if(typeof toast==='function')toast('拍賣後台載入失敗：'+e.message)}finally{S.busy=false}}
async function createOfficial(){try{const snap=JSON.parse(el('aaOfficialJson').value);if(!snap||typeof snap!=='object'||!String(snap.name||'').trim())throw new Error('拍品 JSON 必須包含 name');const price=Number(el('aaOfficialPrice').value);const startText=el('aaOfficialStart').value;const start=new Date(startText);if(!Number.isFinite(price)||price<1||!startText||isNaN(start.getTime()))throw new Error('請確認價格與開始時間');const id=await rpc('auction_create_official',{p_item_snapshot:snap,p_start_price:price,p_starts_at:start.toISOString(),p_minutes:Number(el('aaOfficialMinutes').value)||30});if(typeof addLog==='function')addLog('投放官方拍品 '+id);if(typeof toast==='function')toast('官方拍品已投放');S.tab='history';renderTabs();await searchHistory(false);render()}catch(e){if(typeof toast==='function')toast('投放失敗：'+e.message)} }
async function searchHistory(doRender=true){try{S.auctions=await rpc('auction_admin_list',{p_status:el('aaStatus')?.value||'all',p_search:el('aaSearch')?.value?.trim()||null,p_limit:200})||[];if(doRender)renderHistory()}catch(e){if(typeof toast==='function')toast('拍賣紀錄查詢失敗：'+e.message)}}
function renderHistory(){const box=el('aaHistoryRows');if(!box)return;box.innerHTML=S.auctions.map(a=>`<div class="auction-admin-row"><div><strong>${h(itemName(a.item_snapshot))}</strong> ${a.is_official?'<span class="auction-admin-badge">官方</span>':''}<small>${h(a.id)}｜${h(a.seller_name||'未命名')}｜${h(a.seller_id||'-')}</small></div><div><b>${fmt(a.current_price)} 元寶</b><small>${h(a.status)}｜出價 ${Number(a.bid_count||0)}｜${a.ends_at?new Date(a.ends_at).toLocaleString('zh-TW'):'-'}</small></div><div class="auction-admin-actions">${!['settled','cancelled'].includes(a.status)?`<button type="button" class="btn red" data-force-end="${h(a.id)}">強制結束</button>`:''}</div></div>`).join('')||'<div class="notice">查無拍賣紀錄。</div>';box.querySelectorAll('[data-force-end]').forEach(b=>b.addEventListener('click',()=>forceEnd(b.dataset.forceEnd)))}
async function forceEnd(id){if(!window.confirm('確定強制結束此拍賣並立即結算？'))return;try{await rpc('auction_admin_force_end',{p_auction_id:id});if(typeof addLog==='function')addLog('強制結束拍賣 '+id);if(typeof toast==='function')toast('已強制結束並結算');await searchHistory(true)}catch(e){if(typeof toast==='function')toast('強制結束失敗：'+e.message)}}
async function searchTx(doRender=true){try{const raw=el('aaPlayerId')?.value?.trim()||'';S.tx=await rpc('auction_admin_player_transactions',{p_user_id:raw||null,p_limit:500})||[];if(doRender)renderTx()}catch(e){if(typeof toast==='function')toast('交易紀錄查詢失敗：'+e.message)}}
function renderTx(){const box=el('aaTxRows');if(!box)return;box.innerHTML=S.tx.map(x=>`<div class="auction-admin-row"><div><strong>${h(x.event_type)}</strong><small>${h(x.user_id||'-')}｜拍賣 ${h(x.auction_id||'-')}</small></div><div><b>${fmt(x.amount)} 元寶</b><small>${x.event_time?new Date(x.event_time).toLocaleString('zh-TW'):'-'}</small></div><div></div></div>`).join('')||'<div class="notice">查無交易紀錄。</div>'}
async function saveConfig(){try{const times=el('aaTimes').value.split(',').map(x=>x.trim()).filter(Boolean);if(!times.length||times.some(x=>!/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(x)))throw new Error('場次格式必須為 HH:MM，例如 12:30,20:00');const patch={enabled:el('aaEnabled').value==='true',session_times:times,session_duration_minutes:Number(el('aaDuration').value),min_start_price:Number(el('aaMinPrice').value),bid_increment:Number(el('aaIncrement').value),daily_listing_limit:Number(el('aaDailyLimit').value),anti_snipe_threshold_seconds:Number(el('aaThreshold').value),anti_snipe_extension_seconds:Number(el('aaExtension').value),official_seller_name:el('aaOfficialName').value.trim()||'萬寶樓官方'};S.config=await rpc('auction_admin_set_config',{p_patch:patch});if(typeof addLog==='function')addLog('更新拍賣參數');if(typeof toast==='function')toast('拍賣參數已儲存');render()}catch(e){if(typeof toast==='function')toast('參數儲存失敗：'+e.message)}}
function init(){if(!el('auctionAdminCard'))return;renderTabs();render();el('auctionAdminRefresh')?.addEventListener('click',()=>load(false));const oldLoad=window.loadAll;if(typeof oldLoad==='function'&&!oldLoad.__auctionWrapped){const wrapped=async function(){await oldLoad.apply(this,arguments);await load(true)};wrapped.__auctionWrapped=true;window.loadAll=wrapped}setTimeout(()=>{if(!el('adminMain')?.classList.contains('hidden'))load(true)},800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.V144_AUCTION_ADMIN={load,version:'14.4-fix4'};
})();
