(()=>{'use strict';
const state={recipes:[],loaded:false};
const itemName=id=>{try{return (window.IT&&window.IT[String(id)]&&window.IT[String(id)].name)||String(id)}catch(_){return String(id)}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function client(){return window.cloudState?.client||window.sb||window.supabaseClient||null}
async function load(force=false){if(state.loaded&&!force)return state.recipes;const c=client();if(!c)throw new Error('雲端尚未連線');const {data,error}=await c.rpc('craft_recipe_list',{p_include_hidden:false});if(error)throw error;state.recipes=Array.isArray(data)?data:[];state.loaded=true;return state.recipes}
function enough(r){const gg=window.g;if(!gg)return false;return r.ingredients.every(i=>(gg.inv?.[String(i.item_id)]||0)>=Number(i.qty))&&Number(gg.lingshi||0)>=Number(r.lingshi_cost||0)&&Number(gg.lv||1)>=Number(r.min_level||1)}
function card(r){const mats=r.ingredients.map(i=>`<span>${esc(itemName(i.item_id))} ×${Number(i.qty)}</span>`).join(' + ');return `<article class="v145b-recipe"><header><b>${esc(r.name)}</b><em>${Math.round(Number(r.success_rate)*100)}%</em></header><div class="v145b-mats">${mats}</div><div class="v145b-arrow">→ ${esc(itemName(r.output_item_id))} ×${Number(r.output_qty)}</div>${r.description?`<p>${esc(r.description)}</p>`:''}<footer><small>需求 Lv${Number(r.min_level)}${Number(r.lingshi_cost)?`・${Number(r.lingshi_cost)} 靈石`:''}</small><button class="btn gold" data-craft-id="${esc(r.id)}" ${enough(r)?'':'disabled'}>合成</button></footer></article>`}
async function open(){try{const list=await load();const html=`<div class="v145b-book"><h3>萬法譜</h3><p class="small">配方由世界管理後臺即時控制。材料足夠時可直接煉造。</p><div class="v145b-list">${list.length?list.map(card).join(''):'<p class="small">目前沒有公開配方。</p>'}</div><button class="btn" style="width:100%;margin-top:12px" data-close-book>關閉</button></div>`;window.sheet(html);setTimeout(bind,0)}catch(e){window.toast?.('萬法譜載入失敗：'+e.message)}}
function bind(){document.querySelectorAll('[data-craft-id]').forEach(b=>b.addEventListener('click',()=>craft(b.dataset.craftId)));document.querySelector('[data-close-book]')?.addEventListener('click',()=>window.closeOv?.())}
async function craft(id){const r=state.recipes.find(x=>String(x.id)===String(id)),gg=window.g;if(!r||!gg)return;if(!enough(r)){window.toast?.('材料、境界或靈石不足');return}
 for(const i of r.ingredients)gg.inv[String(i.item_id)]-=Number(i.qty);gg.lingshi=Number(gg.lingshi||0)-Number(r.lingshi_cost||0);
 const ok=Math.random()<Number(r.success_rate||1);if(ok){gg.inv[String(r.output_item_id)]=(gg.inv[String(r.output_item_id)]||0)+Number(r.output_qty||1);window.log?.(`煉造成功：${itemName(r.output_item_id)} ×${r.output_qty}`,'lg')}else{if(r.failure_returns_materials){for(const i of r.ingredients)gg.inv[String(i.item_id)]=(gg.inv[String(i.item_id)]||0)+Number(i.qty);gg.lingshi+=Number(r.lingshi_cost||0)}window.log?.(`煉造失敗：${r.failure_returns_materials?'材料已返還':'材料化為飛灰'}`,'ld')}
 try{await window.saveGame?.(false)}catch(_){}window.render?.();window.toast?.(ok?'煉造成功':'煉造失敗');open()}
function inject(){if(document.querySelector('[data-v145b-book]'))return;const candidates=[...document.querySelectorAll('button')];const craftBtn=candidates.find(x=>/萬法煉造|煉造/.test(x.textContent||''));if(!craftBtn)return;const b=document.createElement('button');b.type='button';b.className=craftBtn.className;b.dataset.v145bBook='1';b.innerHTML='<span>譜</span>萬法譜';b.addEventListener('click',open);craftBtn.parentElement?.appendChild(b)}
window.openRecipeBook=open;new MutationObserver(inject).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('DOMContentLoaded',inject);setTimeout(inject,1200);
})();
