(()=>{
'use strict';
const BUILD='V14.2-AUCTION-20260720';
const state={tab:'live',rows:[],mine:[],bids:[],claims:[],timer:null,busy:false};
const q=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const client=()=>window.cloudState?.client||null;
const user=()=>window.cloudState?.user||null;
function requireOnline(){if(!client()||!user()){window.toast?.('拍賣場需登入聯網封測伺服器');return false}return true}
function fmt(n){return Number(n||0).toLocaleString('zh-TW')}
function itemLabel(s){if(s?.kind==='equipment')return s.equipment?.name||'未知法寶';return window.IT?.[String(s?.item_id)]?.name||s?.name||('物品 '+s?.item_id)}
function nextSession(){const now=new Date(),targets=[[12,30],[20,0]];for(const [h,m] of targets){const d=new Date(now);d.setHours(h,m,0,0);if(d>now)return d}const d=new Date(now);d.setDate(d.getDate()+1);d.setHours(12,30,0,0);return d}
function remainText(ts){const ms=Math.max(0,new Date(ts)-Date.now()),s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;return `${h?String(h).padStart(2,'0')+':':''}${String(m).padStart(2,'0')}:${String(ss).padStart(2,'0')}`}
async function rpc(name,args={}){const {data,error}=await client().rpc(name,args);if(error)throw error;return data}
async function loadAll(){if(!requireOnline())return;state.busy=true;render();try{await rpc('auction_run_settlement');const [rows,mine,bids,claims]=await Promise.all([rpc('auction_list_live'),rpc('auction_list_mine'),rpc('auction_list_my_bids'),rpc('auction_list_claims')]);state.rows=rows||[];state.mine=mine||[];state.bids=bids||[];state.claims=claims||[]}catch(e){window.toast?.('拍賣資料讀取失敗：'+e.message)}finally{state.busy=false;render()}}
function tabButton(id,text){return `<button class="btn ${state.tab===id?'gold':''}" data-auction-tab="${id}">${text}</button>`}
function card(a){const snap=a.item_snapshot||{},name=itemLabel(snap),mine=user()?.id===a.seller_id,ended=new Date(a.ends_at)<=new Date();return `<article class="auction-card ${a.is_official?'official':''}"><div class="meta"><span>${a.is_official?'<b class="auction-badge">官方珍藏</b>':esc(a.seller_name||'匿名修士')}</span><span>${ended?'待結算':remainText(a.ends_at)}</span></div><h4>${esc(name)}</h4><small>${esc(snap.detail||snap.equipment?.detail||'萬寶樓鑑定中的拍品')}</small><div class="price">${fmt(a.current_price)} 元寶</div><small>出價 ${fmt(a.bid_count)} 次｜最低下次 ${fmt(Number(a.current_price)+100)}</small><button class="btn gold" style="width:100%;margin-top:9px" data-auction-bid="${a.id}" ${mine||ended?'disabled':''}>${mine?'自己的拍品':ended?'等待結算':'加價 100 元寶'}</button></article>`}
function liveView(){if(state.busy)return '<div class="auction-empty">正在感應萬寶樓……</div>';return state.rows.length?`<div class="auction-grid">${state.rows.map(card).join('')}</div>`:'<div class="auction-empty">目前沒有進行中的拍賣。</div>'}
function sellOptions(){const opts=[];for(const [id,n] of Object.entries(window.g?.inv||{})){if(n>0&&window.IT?.[id])opts.push(`<option value="item:${esc(id)}">${esc(window.IT[id].name)} ×${n}</option>`)}for(const e of (window.g?.equipment||[])){opts.push(`<option value="equipment:${esc(e.uid)}">${esc(e.name)} +${Number(e.enhance||0)}</option>`)}return opts.join('')}
function sellView(){return `<div class="auction-note">每日每位玩家最多上架 1 件。起標價最低 100 元寶；拍賣開始後物品不可取回。上架後會先從角色背包移除並立即存檔。</div><div class="auction-form"><label>選擇拍品<select id="auctionSellItem">${sellOptions()||'<option value="">沒有可上架物品</option>'}</select></label><label>起標價<input id="auctionStartPrice" type="number" min="100" step="100" value="100"></label><button class="btn gold" id="auctionCreateBtn">上架下一場拍賣</button></div>`}
function mineView(){const rows=state.mine.map(a=>`<div class="list-row"><div class="grow"><strong>${esc(itemLabel(a.item_snapshot))}</strong><small>${esc(a.status)}｜目前 ${fmt(a.current_price)} 元寶｜${new Date(a.ends_at).toLocaleString('zh-TW')}</small></div></div>`).join('');return rows||'<div class="auction-empty">你尚未上架拍品。</div>'}
function bidsView(){const rows=state.bids.map(a=>`<div class="list-row"><div class="grow"><strong>${esc(itemLabel(a.item_snapshot))}</strong><small>${esc(a.status)}｜你的最高出價 ${fmt(a.my_bid)}｜目前 ${fmt(a.current_price)}</small></div></div>`).join('');return rows||'<div class="auction-empty">你尚未參與競標。</div>'}
function claimsView(){const rows=state.claims.map(c=>`<div class="list-row"><div class="grow"><strong>${c.claim_type==='item'?esc(itemLabel(c.payload)):'元寶返還／成交款'}</strong><small>${c.claim_type==='item'?'待領取拍品':fmt(c.amount)+' 元寶'}｜${new Date(c.created_at).toLocaleString('zh-TW')}</small></div><button class="btn jade" data-auction-claim="${c.id}">領取</button></div>`).join('');return rows||'<div class="auction-empty">沒有待領取項目。</div>'}
function body(){return state.tab==='live'?liveView():state.tab==='sell'?sellView():state.tab==='mine'?mineView():state.tab==='bids'?bidsView():claimsView()}
function render(){const root=q('auctionRoot');if(!root)return;root.innerHTML=`<div class="auction-shell"><div class="auction-head"><div><div class="auction-title">萬寶拍賣場</div><small>每日 12:30、20:00 開場｜最低加價 100｜結標前 60 秒出價自動延長 60 秒</small></div><div class="auction-countdown">下一場 ${remainText(nextSession())}</div></div><div class="auction-tabs">${tabButton('live','今日競拍')}${tabButton('sell','我要上架')}${tabButton('mine','我的拍品')}${tabButton('bids','我的競標')}${tabButton('claims','待領取 '+state.claims.length)}</div>${body()}<button class="btn" id="auctionRefresh">重新整理</button></div>`;bind()}
function bind(){document.querySelectorAll('[data-auction-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.auctionTab;render()}));document.querySelectorAll('[data-auction-bid]').forEach(b=>b.addEventListener('click',()=>placeBid(b.dataset.auctionBid)));document.querySelectorAll('[data-auction-claim]').forEach(b=>b.addEventListener('click',()=>claim(b.dataset.auctionClaim)));q('auctionCreateBtn')?.addEventListener('click',createListing);q('auctionRefresh')?.addEventListener('click',loadAll)}
function open(){if(!requireOnline())return;window.sheet?.('<div id="auctionRoot"></div>');render();loadAll();clearInterval(state.timer);state.timer=setInterval(()=>{if(q('auctionRoot'))render();else clearInterval(state.timer)},1000)}
async function placeBid(id){if(state.busy)return;const a=state.rows.find(x=>String(x.id)===String(id));if(!a)return;const amount=Number(a.current_price)+100;if(!confirm(`確認出價 ${fmt(amount)} 元寶？`))return;state.busy=true;try{await window.walletTransaction?.(-amount,'auction_bid_hold',`auction:${id}:${Date.now()}`);await rpc('auction_place_bid',{p_auction_id:id,p_amount:amount});window.g.yuanbao=window.cloudState.walletBalance;window.saveGame?.(false);window.toast?.('出價成功');await loadAll()}catch(e){try{await window.walletTransaction?.(amount,'auction_bid_rollback',`auction-rollback:${id}:${Date.now()}`)}catch(_){}window.toast?.('出價失敗：'+e.message)}finally{state.busy=false}}
async function createListing(){if(state.busy)return;const raw=q('auctionSellItem')?.value,price=Math.floor(Number(q('auctionStartPrice')?.value));if(!raw||price<100||price%100){window.toast?.('請選擇物品，起標價須為 100 的倍數');return}const [kind,key]=raw.split(':');let snap,undo;if(kind==='equipment'){const idx=window.g.equipment.findIndex(e=>String(e.uid)===key);if(idx<0)return;snap={kind:'equipment',equipment:structuredClone(window.g.equipment[idx])};const removed=window.g.equipment.splice(idx,1)[0];undo=()=>window.g.equipment.splice(idx,0,removed)}else{if(!(window.g.inv[key]>0))return;snap={kind:'item',item_id:key,name:window.IT?.[key]?.name||key,detail:window.IT?.[key]?.detail||''};window.g.inv[key]--;undo=()=>window.g.inv[key]=(window.g.inv[key]||0)+1}state.busy=true;try{window.saveGame?.(false);await new Promise(r=>setTimeout(r,450));await rpc('auction_create_listing',{p_item_snapshot:snap,p_start_price:price,p_seller_name:window.g?.name||'匿名修士'});window.log?.('已將 '+itemLabel(snap)+' 上架萬寶拍賣場。','lg');window.toast?.('上架成功');await loadAll()}catch(e){undo?.();window.saveGame?.(false);window.toast?.('上架失敗，物品已復原：'+e.message)}finally{state.busy=false}}
async function claim(id){if(state.busy)return;state.busy=true;try{const c=state.claims.find(x=>String(x.id)===String(id));if(!c)return;if(c.claim_type==='money'){await window.walletTransaction?.(Number(c.amount),'auction_claim',`auction-claim:${id}`);window.g.yuanbao=window.cloudState.walletBalance}else{const p=c.payload||{};if(p.kind==='equipment')window.g.equipment.push(p.equipment);else window.g.inv[String(p.item_id)]=(window.g.inv[String(p.item_id)]||0)+1;window.saveGame?.(false)}await rpc('auction_mark_claimed',{p_claim_id:id});window.toast?.('領取完成');await loadAll();window.render?.()}catch(e){window.toast?.('領取失敗：'+e.message)}finally{state.busy=false}}
function mount(){if(q('auctionLaunch'))return;const b=document.createElement('button');b.id='auctionLaunch';b.className='auction-launch';b.type='button';b.textContent='萬寶拍賣';b.addEventListener('click',open);document.body.appendChild(b)}
window.openAuctionHouseV142=open;window.V14_AUCTION_BUILD=BUILD;
setTimeout(mount,900);
})();
