/* 修仙大逃殺 V15.5R LIVE EQUIPMENT RENDERER FORMAL
   純前端視覺升級：地圖背景為獨立背板；角色、衣甲、武器及強化靈光依現行角色資料即時更新。
   不修改玩法、數值、物品、功法、怪物、戰鬥、探索、突破、存檔格式、後台或 RPC。 */
(function(){
'use strict';
const VERSION='V15.5R-LIVE-EQUIPMENT-RENDERER-FIX10-20260805';
const ASSET='assets/visual_v155r/';
let syncTimer=null,observer=null,syncQueued=false,sceneProfiles=null;const loadTokens=new Map(),loadedKeys=new Map();
const $id=id=>document.getElementById(id);
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const pct=(v,max)=>max>0?Math.max(0,Math.min(100,v/max*100)):0;
const text=(id,fallback='')=>($id(id)?.textContent||fallback).trim();
const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
function state(){return window.g&&typeof window.g==='object'?window.g:null}
function safeCall(name,...args){const fn=window[name];if(typeof fn!=='function'){window.toast?.('功能尚未載入，請稍後再試');return false}try{fn(...args);return true}catch(err){console.error('[V15.5R LIVE EQUIPMENT] '+name+' failed',err);window.toast?.('功能暫時無法開啟');return false}}
function closeNativeOverlay(){try{window.closeOv?.()}catch(_){}}
function catalogItem(eq){if(!eq)return null;return window.IT?.[String(eq.itemId)]||window.C?.items?.[String(eq.itemId)]||null}
function getEquipment(){const s=state();if(!s)return {weapon:null,armor:null};let weapon=null,armor=null;try{weapon=typeof window.getWeapon==='function'?window.getWeapon():null}catch(_){}try{armor=typeof window.getArmor==='function'?window.getArmor():null}catch(_){}if(!weapon&&Array.isArray(s.equipment))weapon=s.equipment.find(e=>e&&e.uid===s.weaponUid)||null;if(!armor&&Array.isArray(s.equipment))armor=s.equipment.find(e=>e&&e.uid===s.armorUid)||null;return {weapon,armor}}
function equipmentInfo(eq,empty){if(!eq)return {name:empty,rawName:'',meta:'尚未裝備',enhance:0,item:null};const it=catalogItem(eq)||{};const enhance=Math.max(0,num(eq.enhance??eq.strength??eq.level));const raw=eq.name||it.name||empty;return {name:raw+(enhance?` +${enhance}`:''),rawName:raw,meta:eq.type||it.type||it.cat||'已裝備',enhance,item:it}}
function terrainFromName(name){const z=String(name||'');if(/冰火/.test(z))return 'icefire';if(/陰陽海/.test(z))return 'yinyang';if(/海|鎮海/.test(z))return 'sea';if(/樹海|森林|森域|迷霧林/.test(z))return 'forest';if(/沙漠|荒漠|砂海/.test(z))return 'desert';if(/冰原|玄霜/.test(z))return 'ice';if(/北寒|北天|天宮/.test(z))return 'northpalace';if(/崑崙|山/.test(z))return 'mountain';if(/古戰場|戰場/.test(z))return 'battle';if(/遺跡/.test(z))return 'ruin';if(/魔淵|深淵/.test(z))return 'abyss';if(/青牛|村|坊市|交易所|丹房|靈泉|神祠|傳訊台/.test(z))return 'village';return 'land'}
function poseForTerrain(t){return ['sea','yinyang','icefire','northpalace','ice'].includes(t)?'flight':'ground'}
function visualGender(s){const v=String(s?.visualProfile?.gender||s?.gender||s?.sex||'').toLowerCase();return /女|female|woman|^f$/.test(v)?'female':'male'}
function setVisualGender(gender){const s=state();if(!s)return;s.visualProfile=(s.visualProfile&&typeof s.visualProfile==='object')?s.visualProfile:{};s.visualProfile.gender=gender;try{window.saveGame?.(false)}catch(_){}sync(true)}
function weaponClass(info){const n=(info.rawName||'')+' '+(info.meta||'');if(!info.rawName)return 'none';if(/雙儀斬仙劍|斬仙/.test(n))return 'signature';return 'sword'}
function armorClass(info){const n=(info.rawName||'')+' '+(info.meta||'');if(!info.rawName)return 'plain';if(/北辰玄冰甲|玄冰/.test(n))return 'icearmor';if(/重甲|鎧|甲/.test(n))return 'heavy';if(/法袍|道袍|袍/.test(n))return 'robe';return 'robe'}
const NAV={home:'home.svg',explore:'explore.svg',meditate:'meditate.svg',bag:'bag.svg',more:'more.svg'};
function createHud(game){if($id('v154uiMobileHud'))return;const hud=document.createElement('div');hud.id='v154uiMobileHud';hud.className='v154ui-mobile-hud';hud.innerHTML=`<button type="button" class="v154ui-avatar-button" id="v154uiAvatarButton" aria-label="開啟個人資訊"><img id="v154uiAvatar" src="${ASSET}avatars/male.webp" alt="角色頭像"></button><div class="v154ui-hud-core"><div class="v154ui-name-line"><strong class="v154ui-name" id="v154uiName">無名散修</strong><span class="v154ui-level" id="v154uiLevel">Lv1</span></div><div class="v154ui-realm" id="v154uiRealm">練氣一層</div><div class="v154ui-bar-row"><span>HP</span><div class="v154ui-bar-track"><i class="v154ui-bar-fill hp" id="v154uiHpFill"></i></div><span class="v154ui-bar-value" id="v154uiHpText">0/0</span></div><div class="v154ui-bar-row"><span>MP</span><div class="v154ui-bar-track"><i class="v154ui-bar-fill mp" id="v154uiMpFill"></i></div><span class="v154ui-bar-value" id="v154uiMpText">0/0</span></div></div><div class="v154ui-hud-currency"><span class="v154ui-currency-pill">靈石 <b id="v154uiLingshi">0</b></span><span class="v154ui-currency-pill">元寶 <b id="v154uiYuanbao">0</b></span></div>`;game.insertBefore(hud,game.firstChild);$id('v154uiAvatarButton')?.addEventListener('click',openProfile)}
function createSceneVisual(){const scene=document.querySelector('#game .world-scene');if(!scene)return;const old=$id('v154vsScene');if(old&&old.dataset.renderer!=='v155r')old.remove();if($id('v154vsScene'))return;const root=document.createElement('div');root.id='v154vsScene';root.className='v154vs-scene v155r-scene v155r-pending';root.dataset.renderer='v155r';root.dataset.integrated='1';root.setAttribute('aria-hidden','true');root.innerHTML=`<div class="v155r-backdrop-stage"><img class="v155r-backdrop" id="v155rBackdrop" alt=""><div class="v155r-backdrop-light"></div></div><div class="v154vs-beast" id="v154vsBeast"><img id="v154vsBeastImg" alt=""></div><div class="v155r-actor-stage" id="v155rActorStage"><div class="v155r-contact-shadow"></div><div class="v155r-actor-stack"><img class="v155r-layer v155r-base" id="v155rBase" alt="角色本體"><img class="v155r-layer v155r-armor" id="v155rArmor" alt="目前衣甲"><div class="v155r-weapon-aura"></div><img class="v155r-layer v155r-weapon" id="v155rWeapon" alt="目前武器"><div class="v155r-actor-light"></div></div></div><div class="v154vs-particles" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="v155r-foreground"></div>`;scene.insertBefore(root,scene.firstChild)}
function createSceneActions(){const scene=document.querySelector('#game .world-scene'),card=document.querySelector('#game .world-scene .scene-content');if(!scene||!card||$id('v154uiSceneActions'))return;const actions=document.createElement('div');actions.id='v154uiSceneActions';actions.className='v154ui-scene-actions';actions.innerHTML=`<button type="button" id="v154uiArtifactAction" aria-label="開啟天工器紋"><span>紋</span><b>天工器紋</b></button><button type="button" id="v154uiCraftsmanAction" aria-label="開啟絕世神匠"><span>匠</span><b>絕世神匠</b><small id="v154uiCraftsmanState">尋訪中</small></button>`;card.appendChild(actions);$id('v154uiArtifactAction')?.addEventListener('click',()=>safeCall('openArtifactWorkshopV143'));$id('v154uiCraftsmanAction')?.addEventListener('click',()=>safeCall('openCrafting','legendary'))}
function createProfile(){if($id('v154uiProfile'))return;const root=document.createElement('section');root.id='v154uiProfile';root.className='v154ui-profile';root.setAttribute('aria-hidden','true');root.innerHTML=`<div class="v154ui-page"><header class="v154ui-page-head"><button type="button" class="v154ui-back" id="v154uiProfileBack">‹</button><div class="v154ui-page-title">個人資訊</div><span></span></header><main class="v154ui-profile-body"><section class="v154ui-hero-card"><div class="v154ui-profile-visual v155r-profile-stage"><div class="v155r-profile-stack"><img class="v155r-profile-layer" id="v155rProfileBase" alt="角色本體"><img class="v155r-profile-layer" id="v155rProfileArmor" alt="目前衣甲"><img class="v155r-profile-layer" id="v155rProfileWeapon" alt="目前武器"></div></div><div class="v154ui-hero-info"><div class="v154ui-profile-name" id="v154uiProfileName">無名散修</div><div class="v154ui-profile-realm" id="v154uiProfileRealm">練氣一層</div><div class="v154ui-profile-level" id="v154uiProfileLevel">Lv1</div><div class="v154ui-gender-choice"><button type="button" data-v154gender="male">男修外觀</button><button type="button" data-v154gender="female">女修外觀</button></div><div class="v154ui-profile-stats"><div class="v154ui-profile-stat"><span>生命</span><b id="v154uiProfileHp">0</b></div><div class="v154ui-profile-stat"><span>法力</span><b id="v154uiProfileMp">0</b></div><div class="v154ui-profile-stat"><span>攻擊</span><b id="v154uiProfileAtk">0</b></div><div class="v154ui-profile-stat"><span>防禦</span><b id="v154uiProfileDef">0</b></div></div></div></section><section class="v154ui-equip-row"><div class="v154ui-equip-slot"><small>武器</small><strong id="v154uiWeapon">空手</strong><span id="v154uiWeaponMeta">尚未裝備</span></div><div class="v154ui-equip-slot"><small>防具</small><strong id="v154uiArmor">無</strong><span id="v154uiArmorMeta">尚未裝備</span></div></section><section class="v154ui-tech-card"><div class="v154ui-section-label">已學功法</div><div class="v154ui-tech-list" id="v154uiTechList"></div></section></main></div>`;document.body.appendChild(root);$id('v154uiProfileBack')?.addEventListener('click',closeProfile);root.querySelectorAll('[data-v154gender]').forEach(b=>b.addEventListener('click',()=>setVisualGender(b.dataset.v154gender)))}
function moreButton(icon,label,sub,action,id=''){return `<button type="button" class="v154ui-more-button" ${id?`id="${id}"`:''} data-action="${action}"><b>${icon}</b><span>${label}</span><small>${sub}</small></button>`}
function createMore(){if($id('v154uiMore'))return;const root=document.createElement('section');root.id='v154uiMore';root.className='v154ui-more';root.setAttribute('aria-hidden','true');root.innerHTML=`<div class="v154ui-page"><header class="v154ui-page-head"><button type="button" class="v154ui-back" id="v154uiMoreBack">‹</button><div class="v154ui-page-title">更多功能</div><span></span></header><main class="v154ui-more-body"><div class="v154ui-more-summary"><strong id="v154uiMoreZone">當前地域</strong><span id="v154uiMoreStatus">選擇要進行的操作</span></div><div class="v154ui-more-grid">${moreButton('圖','御風地圖','選擇目的地','openWorldMap')}${moreButton('坊','商城坊市','交易與功法','openShop')}${moreButton('破','境界突破','達成條件後突破','openBreak','v154uiBreakMore')}${moreButton('煉','萬法煉造','煉丹、煉器與鍛造','openCrafting')}${moreButton('音','全服傳音','查看世界訊息','openWorldChat')}${moreButton('獸','妖獸圖鑑','查看既有妖獸','openMonsterDex')}${moreButton('教','新手教學','玩法操作說明','openTutorial')}${moreButton('雲','雲端狀態','查看同步狀態','openCloudStatus')}${moreButton('報','問題回報','回報遊戲問題','openFeedback')}</div><div class="v154ui-more-note">本頁只整理既有功能入口。</div></main></div>`;document.body.appendChild(root);$id('v154uiMoreBack')?.addEventListener('click',closeMore);root.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>{const name=btn.dataset.action;closeMore();if(name==='openTutorial'){safeCall(name,0);return}if(name==='openCrafting'){safeCall(name,'alchemy');return}safeCall(name)}))}
function navButton(action,label,active=false){return `<button type="button" class="${active?'v154ui-active':''}" data-v154nav="${action}" aria-label="${label}"><span class="v154ui-nav-medallion"><img src="${ASSET}nav/${NAV[action]}" alt=""></span><span class="v154ui-nav-label">${label}</span><i aria-hidden="true"></i></button>`}
function setActiveNav(action){const nav=document.querySelector('#game .mobile-nav');if(!nav)return;nav.querySelectorAll('[data-v154nav]').forEach(btn=>btn.classList.toggle('v154ui-active',btn.dataset.v154nav===action))}
function installNav(game){const nav=game.querySelector('.mobile-nav');if(!nav)return;nav.innerHTML=navButton('home','首頁',true)+navButton('explore','探索')+navButton('meditate','修行')+navButton('bag','背包')+navButton('more','更多');nav.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.dataset.v154nav;setActiveNav(a);if(a==='home'){closeNativeOverlay();closeProfile();closeMore()}else if(a==='explore')safeCall('explore');else if(a==='meditate')safeCall('meditationButtonClick');else if(a==='bag')safeCall('openBag');else if(a==='more')openMore()}))}
function techniqueRows(){const s=state(),ids=Array.isArray(s?.techniques)?s.techniques.slice(0,3):[],catalog=Array.isArray(window.C?.techniques)?window.C.techniques:[];const rows=ids.map((id,i)=>{const t=catalog.find(x=>x&&x.id===id)||{};return {icon:['劍','息','法'][i]||'訣',name:t.name||String(id),desc:t.desc||t.category||'已研習功法'}});while(rows.length<3)rows.push({icon:'訣',name:'尚未研習',desc:'功法欄位保留'});return rows}
function normalizeBeastArray(raw){if(!raw)return[];if(Array.isArray(raw))return raw;if(Array.isArray(raw.beasts))return raw.beasts;if(Array.isArray(raw.states))return raw.states;if(typeof raw==='object')return Object.values(raw).filter(x=>x&&typeof x==='object');return[]}
function findWorldBeast(coord){const candidates=[window.__V151_DIVINE_BEAST_SNAPSHOT,window.V151_DIVINE_BEAST_SNAPSHOT,window.XIANXIA_DIVINE_BEAST_WORLD,window.XIANXIA_DIVINE_BEASTS,window.divineBeastWorld,window.divineBeastStates,state()?.divineBeasts];for(const raw of candidates){for(const b of normalizeBeastArray(raw)){const status=String(b.status||b.state||'').toLowerCase();const active=!status||/active|spawn|alive|現世|出現/.test(status);if(active&&String(b.coord||b.coordinate||'').toUpperCase()===String(coord||'').toUpperCase())return b}}return null}
function beastKind(input){const s=String(input?.beast_key||input?.key||input?.beast_name||input?.name||input||'').toLowerCase();if(/青龍|dragon|azure/.test(s))return'dragon';if(/白虎|tiger/.test(s))return'tiger';if(/鳳凰|phoenix|vermillion/.test(s))return'phoenix';if(/玄武|tortoise|turtle/.test(s))return'tortoise';if(/麒麟|qilin|kirin/.test(s))return'qilin';return''}
function fallbackBeast(terrain){return ({sea:'dragon',yinyang:'dragon',ice:'tiger',forest:'qilin',mountain:'dragon',northpalace:'tiger',icefire:'phoenix',desert:'qilin',battle:'tortoise',ruin:'tortoise'})[terrain]||''}
function syncSceneActions(zoneName){const terrain=terrainFromName(zoneName),craft=$id('v154uiCraftsmanAction'),scene=document.querySelector('#game .world-scene');scene?.setAttribute('data-v154-terrain',terrain);if(craft){craft.hidden=terrain!=='icefire';const m=state()?.masterCraftsman||{};const st=$id('v154uiCraftsmanState');if(st)st.textContent=m.available?'願意鍛造':(m.encounters>0?'再次尋訪':'尋訪神匠')}}
function backgroundSource(terrain){const key=({sea:'sea',yinyang:'yinyang',ice:'ice',forest:'forest',desert:'desert',mountain:'mountain',northpalace:'northpalace',icefire:'icefire',battle:'battle',ruin:'ruin',village:'village',land:'land',abyss:'abyss'})[terrain]||'land';return `${ASSET}backgrounds/${key}.webp`}
function integratedSceneSource(terrain,gender){const key=({sea:'sea',yinyang:'yinyang',ice:'ice',forest:'forest',desert:'desert',mountain:'mountain',northpalace:'northpalace',icefire:'icefire',battle:'battle',ruin:'ruin',village:'village',land:'land',abyss:'abyss'})[terrain]||'land';return `${ASSET}fullscenes/${key}_${gender}.webp`}
function layerSource(kind,gender,pose,value){if(kind==='base')return `${ASSET}characters/${gender}_${pose}.webp`;if(kind==='armor')return `${ASSET}armor/${value}/${gender}_${pose}.webp`;if(kind==='weapon')return `${ASSET}weapons/${value}/${gender}_${pose}.webp`;return ''}
function setLayerImage(img,key,candidates,kind){if(!img)return;const slot=img.id||kind;if(loadedKeys.get(slot)===key)return;const token=(loadTokens.get(slot)||0)+1;loadTokens.set(slot,token);let i=0;const attempt=()=>{if(loadTokens.get(slot)!==token)return;if(i>=candidates.length){img.removeAttribute('src');img.dataset.layerError='1';console.error('[V15.5R LIVE EQUIPMENT] layer unavailable',kind,key,candidates);return}const src=candidates[i++],probe=new Image();probe.decoding='async';probe.onload=()=>{if(loadTokens.get(slot)!==token)return;img.src=src;img.dataset.visualSource=src;delete img.dataset.layerError;loadedKeys.set(slot,key)};probe.onerror=attempt;probe.src=src};attempt()}
function applyProfile(root,terrain){const p=sceneProfiles?.terrains?.[terrain];if(!root||!p)return;root.style.setProperty('--char-left',p.left);root.style.setProperty('--char-bottom',p.bottom);root.style.setProperty('--char-width',p.width);root.style.setProperty('--actor-brightness',String(p.brightness));root.style.setProperty('--actor-saturate',String(p.saturate));root.dataset.temperature=p.temperature||'neutral';root.dataset.foreground=p.foreground||'mist'}
function syncLayerSet(ids,gender,pose,weapon,armor){const base=$id(ids.base),arm=$id(ids.armor),wp=$id(ids.weapon);setLayerImage(base,`${gender}|${pose}|base`,[layerSource('base',gender,pose),layerSource('base','male','ground')],'base');setLayerImage(arm,`${gender}|${pose}|${armor}`,[layerSource('armor',gender,pose,armor),layerSource('armor',gender,pose,'plain')],'armor');setLayerImage(wp,`${gender}|${pose}|${weapon}`,[layerSource('weapon',gender,pose,weapon),layerSource('weapon',gender,pose,'none')],'weapon')}
function syncVisual(zoneName,coord,w,a){const s=state();if(!s)return;const terrain=terrainFromName(zoneName),profile=sceneProfiles?.terrains?.[terrain],pose=profile?.pose||poseForTerrain(terrain),gender=visualGender(s),weapon=weaponClass(w),armor=armorClass(a),enhance=w.enhance||0;const root=$id('v154vsScene'),backdrop=$id('v155rBackdrop');if(!root||!backdrop)return;root.dataset.terrain=terrain;root.dataset.pose=pose;root.dataset.gender=gender;root.dataset.weapon=weapon;root.dataset.armor=armor;root.dataset.coord=coord||'';root.classList.toggle('v155r-enhance8',enhance>=8&&enhance<12);root.classList.toggle('v155r-enhance12',enhance>=12);applyProfile(root,terrain);setLayerImage(backdrop,`backdrop|${terrain}|${gender}`,[integratedSceneSource(terrain,gender),integratedSceneSource(terrain,'male'),backgroundSource(terrain),backgroundSource('land')],'backdrop');root.classList.add('v155r-use-integrated');root.classList.remove('v155r-pending');syncLayerSet({base:'v155rBase',armor:'v155rArmor',weapon:'v155rWeapon'},gender,pose,weapon,armor);syncLayerSet({base:'v155rProfileBase',armor:'v155rProfileArmor',weapon:'v155rProfileWeapon'},gender,'ground',weapon,armor);const avatar=`${ASSET}avatars/${gender}.webp`;const av=$id('v154uiAvatar');if(av&&av.getAttribute('src')!==avatar)av.setAttribute('src',avatar);document.querySelectorAll('[data-v154gender]').forEach(b=>b.classList.toggle('on',b.dataset.v154gender===gender));const world=findWorldBeast(coord),kind=beastKind(world)||fallbackBeast(terrain),beast=$id('v154vsBeast'),bi=$id('v154vsBeastImg');if(beast&&bi){if(root.dataset.integrated==='1'){beast.hidden=true}else{beast.hidden=!kind;if(kind){bi.src=`${ASSET}beasts/${kind}.svg`;beast.dataset.kind=kind;beast.dataset.source=world?'world':'ecology'}}}root.dispatchEvent(new CustomEvent('v155r:visual-synced',{detail:{terrain,gender,pose,weapon,armor,enhance,coord,layers:{base:layerSource('base',gender,pose),armor:layerSource('armor',gender,pose,armor),weapon:layerSource('weapon',gender,pose,weapon)}}}))}
function queueSync(force=false){if(syncQueued&&!force)return;syncQueued=true;requestAnimationFrame(()=>{syncQueued=false;sync(force)})}
function sync(force=false){const s=state();if(!s)return;const hp=Math.round(num(s.hp)),hpMax=Math.max(1,Math.round(num(s.hpMax))),mp=Math.round(num(s.mp)),mpMax=Math.max(1,Math.round(num(s.mpMax)));const realm=text('prealm',`${s.big||'練氣'} · Lv${s.lv||1}`),name=s.name||text('pname','無名散修');const set=(id,v)=>{const el=$id(id);if(el)el.textContent=v};set('v154uiName',name);set('v154uiLevel','Lv'+(s.lv||1));set('v154uiRealm',realm);set('v154uiHpText',`${hp}/${hpMax}`);set('v154uiMpText',`${mp}/${mpMax}`);if($id('v154uiHpFill'))$id('v154uiHpFill').style.width=pct(hp,hpMax)+'%';if($id('v154uiMpFill'))$id('v154uiMpFill').style.width=pct(mp,mpMax)+'%';set('v154uiLingshi',num(s.lingshi).toLocaleString());set('v154uiYuanbao',num(s.yuanbao).toLocaleString());set('v154uiProfileName',name);set('v154uiProfileRealm',realm);set('v154uiProfileLevel','等級 Lv.'+(s.lv||1));set('v154uiProfileHp',`${hp}/${hpMax}`);set('v154uiProfileMp',`${mp}/${mpMax}`);let atk=text('atk','0'),def=text('def','0');try{if(typeof window.pAtk==='function')atk=String(window.pAtk())}catch(_){}try{if(typeof window.pDef==='function')def=String(window.pDef())}catch(_){}set('v154uiProfileAtk',atk);set('v154uiProfileDef',def);const eq=getEquipment(),w=equipmentInfo(eq.weapon,'空手'),a=equipmentInfo(eq.armor,'無');set('v154uiWeapon',w.name);set('v154uiWeaponMeta',w.meta);set('v154uiArmor',a.name);set('v154uiArmorMeta',a.meta);const tech=$id('v154uiTechList');if(tech)tech.innerHTML=techniqueRows().map(x=>`<div class="v154ui-tech-item"><span class="v154ui-tech-icon">${x.icon}</span><div class="v154ui-tech-copy"><strong>${esc(x.name)}</strong><span>${esc(x.desc)}</span></div></div>`).join('');const zone=text('sceneZone','當前地域'),coord=text('sceneCoord','').split('·')[0].trim();set('v154uiMoreZone',zone);set('v154uiMoreStatus',text('worldStatus','選擇要進行的操作'));syncSceneActions(zone);if(force){loadedKeys.clear();for(const k of loadTokens.keys())loadTokens.set(k,(loadTokens.get(k)||0)+1)}syncVisual(zone,coord,w,a);const breakSource=$id('brkBtn'),breakMore=$id('v154uiBreakMore');if(breakMore)breakMore.disabled=!!breakSource?.disabled}
function openProfile(){createProfile();sync(true);setActiveNav('home');const p=$id('v154uiProfile');if(p){p.classList.add('on');p.setAttribute('aria-hidden','false')}}
function closeProfile(){const p=$id('v154uiProfile');if(p){p.classList.remove('on');p.setAttribute('aria-hidden','true')}}
function openMore(){createMore();sync();const p=$id('v154uiMore');if(p){p.classList.add('on');p.setAttribute('aria-hidden','false')}}
function closeMore(){const p=$id('v154uiMore');if(p){p.classList.remove('on');p.setAttribute('aria-hidden','true')}}
function install(){const game=$id('game');if(!game||game.dataset.v155rLiveEquipment==='installed')return;game.dataset.v155rLiveEquipment='installed';delete game.dataset.v155LiveCharacter;try{window.V144_FIXED_MAP?.updateCurrentScene?.()}catch(_){}createHud(game);createSceneVisual();createSceneActions();createProfile();createMore();installNav(game);const ids=['pname','prealm','hpText','mpText','atk','def','ls','yb','wp','armor','sceneZone','sceneCoord','worldStatus','techniqueDock'];observer=new MutationObserver(()=>queueSync());ids.forEach(id=>{const el=$id(id);if(el)observer.observe(el,{subtree:true,childList:true,characterData:true,attributes:true})});syncTimer=setInterval(()=>queueSync(),180);document.addEventListener('visibilitychange',()=>{if(!document.hidden)queueSync(true)});window.addEventListener('pageshow',()=>queueSync(true));window.addEventListener('storage',()=>queueSync(true));window.addEventListener('resize',()=>queueSync(true),{passive:true});fetch(ASSET+'config/scene_profiles.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(x=>{if(x?.terrains){sceneProfiles=x;queueSync(true)}}).catch(()=>{});setTimeout(()=>{try{window.V144_FIXED_MAP?.updateCurrentScene?.()}catch(_){}sync(true)},120);window.openV154MobileProfile=openProfile;window.closeV154MobileProfile=closeProfile;window.openV154MobileMore=openMore;window.closeV154MobileMore=closeMore;window.setV154VisualGender=setVisualGender;window.V155R_LIVE_EQUIPMENT_RENDERER={version:VERSION,sync:()=>queueSync(true),getVisualState:()=>{const r=$id('v154vsScene');return r?{terrain:r.dataset.terrain,pose:r.dataset.pose,gender:r.dataset.gender,weapon:r.dataset.weapon,armor:r.dataset.armor,base:$id('v155rBase')?.dataset.visualSource,armorSource:$id('v155rArmor')?.dataset.visualSource,weaponSource:$id('v155rWeapon')?.dataset.visualSource}:null}};console.info('[V15.5R LIVE EQUIPMENT RENDERER] installed',VERSION)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();setTimeout(install,0);
})();
